sudo: required
services:
  - docker

before_install:
  - docker build -t jameelvm1/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true jameelvm1/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  regions: "us-west-2"
  app: "JKubernetesDeployment"
  env: "JKubernetesDeployment-env"
  bucket_name: "elasticbeanstalk-us-west-2-268310970254"
  bucket_path: "JKubernetesDeployment"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"


